# Import library and data

In [1]:
import pandas as pd
import numpy as np
q=pd.read_csv('athlete_events.csv')
q.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

# Information about dataset

In [2]:
# # returns a tuple of array dimension that specifies the number of rows and columns
q.shape

(271116, 15)

In [57]:
# prints the information about the dataframe
q.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 270767 entries, 0 to 270766
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   ID              270767 non-null  int64  
 1   Name            270767 non-null  object 
 2   Sex             270767 non-null  object 
 3   Age             261305 non-null  float64
 4   Height          210684 non-null  float64
 5   Weight          207982 non-null  float64
 6   Team            270767 non-null  object 
 7   NOC             270767 non-null  object 
 8   Games           270767 non-null  object 
 9   Year            270767 non-null  int64  
 10  Season          270767 non-null  object 
 11  City            270767 non-null  object 
 12  Sport           270767 non-null  object 
 13  Event           270767 non-null  object 
 14  Medal           270767 non-null  object 
 15  region          270746 non-null  object 
 16  BMI             206599 non-null  float64
 17  classifica

In [61]:
# check for missing values and handle them
q.isnull().sum()

ID                    0
Name                  0
Sex                   0
Age                9462
Height            60083
Weight            62785
Team                  0
NOC                   0
Games                 0
Year                  0
Season                0
City                  0
Sport                 0
Event                 0
Medal                 0
region               21
BMI               64168
classification        0
name_length           0
dtype: int64

In [62]:
# check for duplicate values
q.duplicated().any()

True

In [63]:
# check all columns of dataset
q.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal', 'region', 'BMI',
       'classification', 'name_length'],
      dtype='object')

In [5]:
# merge with NOC regin to add 'Region' columns
q=q.merge(pd.read_csv('noc_regions.csv'),on='NOC').drop(columns=['notes'])

# Women In The Olympics Before World War 2

Find unique names women who participated in an Olympics before World War 2. Let's consider the year 1939 as the start of WW2.




In [6]:
q.loc[(q.Year<1939)&(q.Sex=='F'),['Name','Sex','Team','Games']]

Name Sex  \
1637                                         Li Sen   F   
4277                                  Yeung Sauking   F   
4278                                  Yeung Sauking   F   
5150                  Else Margrethe Ahlmann-Ohlsen   F   
5230    Karen Margrete Andersen (Friis-, -Jrgensen)   F   
...                                             ...  ..   
260789                                   Ivka Tavar   F   
260899                                    Maja Vere   F   
261680  Antonia Matos (Matos Aycinena-, -de Massot)   F   
269448    Hedwiga Rosenbaumov (Austerlitz-, -Raabe)   F   
269449    Hedwiga Rosenbaumov (Austerlitz-, -Raabe)   F   

                         Team        Games  
1637                    China  1936 Summer  
4277                    China  1936 Summer  
4278                    China  1936 Summer  
5150                  Denmark  1928 Summer  
5230                  Denmark  1936 Summer  
...                       ...          ...  
260789             Yugoslavia  1936 Summer  
260899             Yugoslavia  1936 Summer  
261680              Guatemala  1932 Summer  
269448                Bohemia  1900 Summer  
269449  Bohemia/Great Britain  1900 Summer  

[1944 rows x 4 columns]

# Find the number of athletes that participated in each Olympics season

Find the number of athletes that participated in each Olympics season.
Output the season with the corresponding number of athletes.

In [7]:
q.groupby(['Season'])['ID'].count().reset_index().rename(columns={'ID':'total_athletes'})

Season  total_athletes
0  Summer          222203
1  Winter           48564

# London Olympic Swimmers


Find the athletes who competed in swimming events at the London Olympics.



In [9]:
q[(q.Sport=='Swimming')&(q.City=='London')]

ID                      Name Sex   Age  Height  Weight  \
20        6847                  Bai Anqi   F  19.0   164.0    59.0   
132      20159                Chen Cheng   M  20.0   184.0    77.0   
223      20251                 Chen Qian   F  19.0   175.0    58.0   
296      20313                  Chen Yin   M  26.0   182.0    76.0   
352      20363               Cheng Feiyi   M  21.0   179.0    73.0   
...        ...                       ...  ..   ...     ...     ...   
270528   85721           Nguyn Th nh Vin   F  15.0   172.0    60.0   
270529   85721           Nguyn Th nh Vin   F  15.0   172.0    60.0   
270659   46168            Giordan Harris   M  19.0   185.0    99.0   
270662   47815  Ann-Marie "Annie" Hepler   F  16.0   167.0    68.0   
270761  119563             Masempe Theko   F  25.0     NaN     NaN   

                    Team  NOC        Games  Year  Season    City     Sport  \
20                 China  CHN  2012 Summer  2012  Summer  London  Swimming   
132                China  CHN  2012 Summer  2012  Summer  London  Swimming   
223                China  CHN  2012 Summer  2012  Summer  London  Swimming   
296                China  CHN  2012 Summer  2012  Summer  London  Swimming   
352                China  CHN  2012 Summer  2012  Summer  London  Swimming   
...                  ...  ...          ...   ...     ...     ...       ...   
270528           Vietnam  VIE  2012 Summer  2012  Summer  London  Swimming   
270529           Vietnam  VIE  2012 Summer  2012  Summer  London  Swimming   
270659  Marshall Islands  MHL  2012 Summer  2012  Summer  London  Swimming   
270662  Marshall Islands  MHL  2012 Summer  2012  Summer  London  Swimming   
270761           Lesotho  LES  2012 Summer  2012  Summer  London  Swimming   

                                                  Event Medal  \
20               Swimming Women's 200 metres Backstroke   NaN   
132              Swimming Men's 200 metres Breaststroke   NaN   
223     Swimming Women's 4 x 200 metres Freestyle Relay   NaN   
296                 Swimming Men's 200 metres Butterfly   NaN   
352                Swimming Men's 100 metres Backstroke   NaN   
...                                                 ...   ...   
270528           Swimming Women's 200 metres Backstroke   NaN   
270529    Swimming Women's 400 metres Individual Medley   NaN   
270659               Swimming Men's 50 metres Freestyle   NaN   
270662             Swimming Women's 50 metres Freestyle   NaN   
270761             Swimming Women's 50 metres Freestyle   NaN   

                  region  
20                 China  
132                China  
223                China  
296                China  
352                China  
...                  ...  
270528           Vietnam  
270529           Vietnam  
270659  Marshall Islands  
270662  Marshall Islands  
270761           Lesotho  

[2077 rows x 16 columns]

# Largest Olympics


Find the Olympics with the highest number of athletes. The Olympics game is a combination of the year and the season, and is found in the 'games' column. Output the Olympics along with the corresponding number of athletes.



In [8]:
# top 3 largest Olympics
q.groupby(['Year','Season'])['ID'].count().reset_index().rename(columns={'ID':'total_athletes'}).nlargest(3,'total_athletes')

Year  Season  total_athletes
42  2000  Summer           13798
40  1996  Summer           13745
50  2016  Summer           13656

# Find all Danish athletes who won a medal

Find all Danish athletes who won a medal.
Output unique names only.


In [10]:
q[(q.region=='Denmark')&(q.Medal=='Gold')].iloc[:,[1,2,8,12,-2]]

Name Sex        Games       Sport Medal
5142                Edgar Lindenau Aabye   M  1900 Summer  Tug-Of-War  Gold
5152    Georg Albert Christian Albertsen   M  1920 Summer  Gymnastics  Gold
5159             Ejler Arild Emil Allert   M  1912 Summer      Rowing  Gold
5162       Aage Jrgen Christian Andersen   M  1906 Summer    Football  Gold
5171                   Anja Jul Andersen   F  1996 Summer    Handball  Gold
...                                  ...  ..          ...         ...   ...
8626  Mette Vestergaard Larsen (-Brandt)   F  2000 Summer    Handball  Gold
8627  Mette Vestergaard Larsen (-Brandt)   F  2004 Summer    Handball  Gold
8647  Christian Robert von Blow af Radum   M  1964 Summer     Sailing  Gold
8660                        Jonas Warrer   M  2008 Summer     Sailing  Gold
8682     Charles Gustav Wilhelm Winckler   M  1900 Summer  Tug-Of-War  Gold

[179 rows x 5 columns]

# Find the year in which the shortest athlete participated

Find the year in which the shortest athlete participated.
Output the year and the corresponding height.


In [11]:
q[q.Height==q.Height.min()].drop_duplicates(['Name','Height','Games'])

ID                   Name Sex   Age  Height  Weight    Team  NOC  \
103795  15150        Rosario Briones   F  15.0   127.0    42.0  Mexico  MEX   
267919  82769  Lyton Levison Mphande   M  25.0   127.0    62.0  Malawi  MAW   

              Games  Year  Season         City       Sport  \
103795  1968 Summer  1968  Summer  Mexico City  Gymnastics   
267919  1988 Summer  1988  Summer        Seoul      Boxing   

                                           Event Medal  region  
103795  Gymnastics Women's Individual All-Around   NaN  Mexico  
267919           Boxing Men's Light-Welterweight   NaN  Malawi

# Find Olympic Events Based On Height

Find events of any Winter Olympics in which there were athletes of height between 180 to 210 centimeters. Output unique events only.




In [12]:
# find the Winter Olympics in which there were athletes of height between 180 to 210 cm
q[(q.Height>=180)&(q.Height<=210)&(q.Season=='Winter')]

ID         Name Sex   Age  Height  Weight     Team  NOC  \
16        6376     Ba Dexin   M  23.0   185.0    80.0    China  CHN   
405      24908  Dai Dengwen   M  21.0   180.0    80.0    China  CHN   
406      24908  Dai Dengwen   M  21.0   180.0    80.0    China  CHN   
408      24910      Dai Jun   M  25.0   180.0    75.0    China  CHN   
409      24910      Dai Jun   M  25.0   180.0    75.0    China  CHN   
...        ...          ...  ..   ...     ...     ...      ...  ...   
270164  120779   Erjon Tola   M  19.0   180.0    74.0  Albania  ALB   
270165  120779   Erjon Tola   M  19.0   180.0    74.0  Albania  ALB   
270166  120779   Erjon Tola   M  19.0   180.0    74.0  Albania  ALB   
270167  120779   Erjon Tola   M  23.0   180.0    74.0  Albania  ALB   
270168  120779   Erjon Tola   M  23.0   180.0    74.0  Albania  ALB   

              Games  Year  Season         City          Sport  \
16      2014 Winter  2014  Winter        Sochi        Curling   
405     1998 Winter  1998  Winter       Nagano  Speed Skating   
406     1998 Winter  1998  Winter       Nagano  Speed Skating   
408     1992 Winter  1992  Winter  Albertville  Speed Skating   
409     1992 Winter  1992  Winter  Albertville  Speed Skating   
...             ...   ...     ...          ...            ...   
270164  2006 Winter  2006  Winter       Torino  Alpine Skiing   
270165  2006 Winter  2006  Winter       Torino  Alpine Skiing   
270166  2006 Winter  2006  Winter       Torino  Alpine Skiing   
270167  2010 Winter  2010  Winter    Vancouver  Alpine Skiing   
270168  2010 Winter  2010  Winter    Vancouver  Alpine Skiing   

                                   Event Medal   region  
16                 Curling Men's Curling   NaN    China  
405       Speed Skating Men's 500 metres   NaN    China  
406     Speed Skating Men's 1,000 metres   NaN    China  
408       Speed Skating Men's 500 metres   NaN    China  
409     Speed Skating Men's 1,000 metres   NaN    China  
...                                  ...   ...      ...  
270164       Alpine Skiing Men's Super G   NaN  Albania  
270165  Alpine Skiing Men's Giant Slalom   NaN  Albania  
270166        Alpine Skiing Men's Slalom   NaN  Albania  
270167  Alpine Skiing Men's Giant Slalom   NaN  Albania  
270168        Alpine Skiing Men's Slalom   NaN  Albania  

[13210 rows x 16 columns]

In [13]:
q[(q.Height>=180)&(q.Height<=210)&(q.Season=='Winter')].drop_duplicates('Games')['Games'].unique()

array(['2014 Winter', '1998 Winter', '1992 Winter', '2006 Winter',
       '2010 Winter', '2002 Winter', '1988 Winter', '1994 Winter',
       '1964 Winter', '1968 Winter', '1980 Winter', '1928 Winter',
       '1984 Winter', '1976 Winter', '1960 Winter', '1972 Winter',
       '1924 Winter', '1956 Winter', '1948 Winter', '1952 Winter',
       '1932 Winter', '1936 Winter'], dtype=object)

# Find all athletes who were older than 40 years when they won either Bronze or Silver medals

Find all athletes who were older than 40 years when they won either Bronze or Silver medals.



In [14]:
q.loc[(q.Medal.str.contains('Bronze|Silver',na=False))&(q.Age>40),['Name','Age','Games','region','Medal']]

Name   Age        Games  \
641                            Gao E  41.0  2004 Summer   
5243                  Niels Andersen  44.0  1912 Summer   
5360    Ole Valdemar Henrik Berntsen  41.0  1956 Summer   
5367         William Eldred Berntsen  48.0  1960 Summer   
5389                   Jane Bidstrup  42.0  1998 Winter   
...                              ...   ...          ...   
248396                    Hugo Simon  49.0  1992 Summer   
248634           Hermann Stiegholzer  42.0  1936 Summer   
248851                  Oskar Thiede  69.0  1948 Summer   
257838           Abdullah Al-Rashidi  52.0  2016 Summer   
270493                 Hong Xun Vinh  41.0  2016 Summer   

                             region   Medal  
641                           China  Bronze  
5243                        Denmark  Bronze  
5360                        Denmark  Silver  
5367                        Denmark  Silver  
5389                        Denmark  Silver  
...                             ...     ...  
248396                      Austria  Silver  
248634                      Austria  Bronze  
248851                      Austria  Silver  
257838  Individual Olympic Athletes  Bronze  
270493                      Vietnam  Silver  

[689 rows x 5 columns]

# Find all events participated by Christine Jacoba Aaftink

Find all events participated by Christine Jacoba Aaftink.
Output unique values only.


In [15]:
q[q.Name.str.contains('Christine Jacoba Aaftink')].drop_duplicates(['Name','Games'])

ID                      Name Sex   Age  Height  Weight         Team  \
8711   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0  Netherlands   
8713   5  Christine Jacoba Aaftink   F  25.0   185.0    82.0  Netherlands   
8715   5  Christine Jacoba Aaftink   F  27.0   185.0    82.0  Netherlands   

      NOC        Games  Year  Season         City          Sport  \
8711  NED  1988 Winter  1988  Winter      Calgary  Speed Skating   
8713  NED  1992 Winter  1992  Winter  Albertville  Speed Skating   
8715  NED  1994 Winter  1994  Winter  Lillehammer  Speed Skating   

                                 Event Medal       region  
8711  Speed Skating Women's 500 metres   NaN  Netherlands  
8713  Speed Skating Women's 500 metres   NaN  Netherlands  
8715  Speed Skating Women's 500 metres   NaN  Netherlands

# Find all minors that participated in Olympics games

Find all minor that participated in Olympics games.
A player is considered as a minor if he or she is older less or equal than 18 years.
Output the name and age of the player along with participated Olympic games (ex: 1992 Summer).


In [16]:
q.loc[q.Age<=18,['Name','Age','Games']]

Name   Age        Games
4                               Ai Yanhan  14.0  2016 Summer
5                               Ai Yanhan  14.0  2016 Summer
26                                Bai Mei  17.0  1992 Summer
35                           Bao Zhenghua  14.0  1980 Winter
36                           Bao Zhenghua  18.0  1984 Winter
...                                   ...   ...          ...
270742  Mantokoane Angelina Pitso Sephooa  17.0  1992 Summer
270743  Mantokoane Angelina Pitso Sephooa  17.0  1992 Summer
270755               Lineo Florence Shoai  17.0  1996 Summer
270756               Lineo Florence Shoai  17.0  1996 Summer
270764                 M'apotlaki Ts'elho  15.0  1996 Summer

[20569 rows x 3 columns]

# Find the Olympic game which had the highest number of participants that didn't earn a medal
Find the Olympic game which had the highest number of participants that didn't earn a medal.
Output the Olympic game name along with the corresponding number of athletes.
Olympic game name consists of the year and the season.

In [17]:
# find all the athletes who didn't earn any medal in Olympic games
q[~q.Medal.str.contains('Gold|Silver|Bronze',na=False)]

ID                Name Sex   Age  Height  Weight     Team  NOC  \
0            1           A Dijiang   M  24.0   180.0    80.0    China  CHN   
1            2            A Lamusi   M  23.0   170.0    60.0    China  CHN   
2          602       Abudoureheman   M  22.0   182.0    75.0    China  CHN   
3         1463           Ai Linuer   M  25.0   160.0    62.0    China  CHN   
4         1464           Ai Yanhan   F  14.0   168.0    54.0    China  CHN   
...        ...                 ...  ..   ...     ...     ...      ...  ...   
270762  120575     Mamorallo Tjoka   F  23.0   150.0    56.0  Lesotho  LES   
270763  120575     Mamorallo Tjoka   F  27.0   150.0    56.0  Lesotho  LES   
270764  122166  M'apotlaki Ts'elho   F  15.0     NaN     NaN  Lesotho  LES   
270765  122215          Lefa Tsapi   M  23.0   170.0    63.0  Lesotho  LES   
270766  122299       Mosolesa Tsie   M  20.0   175.0    75.0  Lesotho  LES   

              Games  Year  Season            City       Sport  \
0       1992 Summer  1992  Summer       Barcelona  Basketball   
1       2012 Summer  2012  Summer          London        Judo   
2       2000 Summer  2000  Summer          Sydney      Boxing   
3       2004 Summer  2004  Summer          Athina   Wrestling   
4       2016 Summer  2016  Summer  Rio de Janeiro    Swimming   
...             ...   ...     ...             ...         ...   
270762  2008 Summer  2008  Summer         Beijing   Athletics   
270763  2012 Summer  2012  Summer          London   Athletics   
270764  1996 Summer  1996  Summer         Atlanta   Athletics   
270765  1984 Summer  1984  Summer     Los Angeles      Boxing   
270766  2000 Summer  2000  Summer          Sydney      Boxing   

                                           Event Medal   region  
0                    Basketball Men's Basketball   NaN    China  
1                   Judo Men's Extra-Lightweight   NaN    China  
2                      Boxing Men's Middleweight   NaN    China  
3       Wrestling Men's Lightweight, Greco-Roman   NaN    China  
4          Swimming Women's 200 metres Freestyle   NaN    China  
...                                          ...   ...      ...  
270762                Athletics Women's Marathon   NaN  Lesotho  
270763                Athletics Women's Marathon   NaN  Lesotho  
270764    Athletics Women's 4 x 100 metres Relay   NaN  Lesotho  
270765                 Boxing Men's Welterweight   NaN  Lesotho  
270766                 Boxing Men's Welterweight   NaN  Lesotho  

[230993 rows x 16 columns]

In [18]:
q[~q.Medal.str.contains('Gold|Silver|Bronze',na=False)].groupby('Games')['ID'].count().reset_index().nlargest(3,'ID').rename(
    columns={'ID':"total no medal"})

Games  total no medal
40  1996 Summer           11903
42  2000 Summer           11794
50  2016 Summer           11634

# Find how many athletes competing in Football won Gold medals by their NOC and gender
Find how many athletes competing in Football won Gold medals by their NOC and gender.
Output the NOC, sex, and the corresponding number of athletes.
Sort records by the NOC, sex, and the number of athletes in ascending order.

In [19]:
# find the athletes who competing in Football won Gold medals
q[(q.Sport=='Football')&(q.Medal.str.contains('Gold'))]

ID                           Name Sex   Age  Height  Weight  \
5162      3684  Aage Jrgen Christian Andersen   M  22.0     NaN     NaN   
5257      3785             Vigo Carl Andersen   M  21.0     NaN     NaN   
5526     16069           Charles von Buchwald   M  25.0     NaN     NaN   
5817     35069             Parmo Karl Ferslev   M  23.0     NaN     NaN   
5866     36941             Holger Frederiksen   M  25.0     NaN     NaN   
...        ...                            ...  ..   ...     ...     ...   
260625  113021               Velimir Sombolac   M  21.0   169.0    71.0   
260628  113314                    Milutin oki   M  22.0   181.0    80.0   
260785  117880                 Silvester Taka   M  19.0   169.0    71.0   
260905  126390                 Blagoja Vidini   M  26.0   194.0    96.0   
261006  133929             Antun "Ante" aneti   M  23.0   173.0    77.0   

              Team  NOC        Games  Year  Season    City     Sport  \
5162       Denmark  DEN  1906 Summer  1906  Summer  Athina  Football   
5257       Denmark  DEN  1906 Summer  1906  Summer  Athina  Football   
5526       Denmark  DEN  1906 Summer  1906  Summer  Athina  Football   
5817       Denmark  DEN  1906 Summer  1906  Summer  Athina  Football   
5866       Denmark  DEN  1906 Summer  1906  Summer  Athina  Football   
...            ...  ...          ...   ...     ...     ...       ...   
260625  Yugoslavia  YUG  1960 Summer  1960  Summer    Roma  Football   
260628  Yugoslavia  YUG  1960 Summer  1960  Summer    Roma  Football   
260785  Yugoslavia  YUG  1960 Summer  1960  Summer    Roma  Football   
260905  Yugoslavia  YUG  1960 Summer  1960  Summer    Roma  Football   
261006  Yugoslavia  YUG  1960 Summer  1960  Summer    Roma  Football   

                          Event Medal   region  
5162    Football Men's Football  Gold  Denmark  
5257    Football Men's Football  Gold  Denmark  
5526    Football Men's Football  Gold  Denmark  
5817    Football Men's Football  Gold  Denmark  
5866    Football Men's Football  Gold  Denmark  
...                         ...   ...      ...  
260625  Football Men's Football  Gold   Serbia  
260628  Football Men's Football  Gold   Serbia  
260785  Football Men's Football  Gold   Serbia  
260905  Football Men's Football  Gold   Serbia  
261006  Football Men's Football  Gold   Serbia  

[515 rows x 16 columns]

In [20]:
q[(q.Sport=='Football')&(q.Medal.str.contains('Gold'))].groupby(['NOC','Sex'])['ID'].count().reset_index().rename(
    columns={'ID':'total_athletes'}).sort_values('total_athletes',ascending=False)

NOC Sex  total_athletes
21  USA   F              66
11  HUN   M              46
8   GBR   M              36
19  URS   M              36
0   ARG   M              34
20  URU   M              31
4   CMR   M              18
10  GER   F              18
15  NOR   F              17
2   BRA   M              17
9   GDR   M              17
16  POL   M              17
6   ESP   M              17
14  NGR   M              16
18  TCH   M              16
22  YUG   M              16
13  MEX   M              16
7   FRA   M              16
12  ITA   M              14
1   BEL   M              14
3   CAN   M              13
17  SWE   M              12
5   DEN   M              12

# Winter Olympics Events List By Age


Find the lowest, average, and the highest ages of athletes across all Olympics. HINT: If athlete participated in more than one discipline at one Olympic games, consider it as a separate athlete, no need to remove such edge cases.

In [21]:
q1=q[q.Season=='Winter']
pd.merge(q1.groupby(['Games','Season']).Age.min().reset_index(),
         q1.groupby(['Games','Season']).Age.mean().reset_index(),on=['Games','Season']).merge(
                    q1.groupby(['Games','Season']).Age.max().reset_index(),on=['Games','Season']).rename(columns={'Age_x':'min_age',
                                                        'Age_y':'avg_age','Age':'max_age'})

Games  Season  min_age    avg_age  max_age
0   1924 Winter  Winter     11.0  27.590571     58.0
1   1928 Winter  Winter     15.0  26.581301     54.0
2   1932 Winter  Winter     11.0  25.547112     52.0
3   1936 Winter  Winter     11.0  25.048643     46.0
4   1948 Winter  Winter     15.0  26.239029     53.0
5   1952 Winter  Winter     12.0  25.446691     47.0
6   1956 Winter  Winter     12.0  25.549922     48.0
7   1960 Winter  Winter     11.0  24.241877     39.0
8   1964 Winter  Winter     13.0  24.419830     53.0
9   1968 Winter  Winter     11.0  24.215812     51.0
10  1972 Winter  Winter     13.0  24.107748     42.0
11  1976 Winter  Winter     12.0  23.739459     46.0
12  1980 Winter  Winter     13.0  23.656160     49.0
13  1984 Winter  Winter     15.0  23.443241     53.0
14  1988 Winter  Winter     11.0  23.840607     52.0
15  1992 Winter  Winter     13.0  24.027948     46.0
16  1994 Winter  Winter     13.0  24.422103     46.0
17  1998 Winter  Winter     14.0  25.163197     50.0
18  2002 Winter  Winter     15.0  25.916281     48.0
19  2006 Winter  Winter     14.0  25.959151     52.0
20  2010 Winter  Winter     15.0  26.124262     51.0
21  2014 Winter  Winter     15.0  25.987324     55.0

# Order all countries by the year they first participated in the Olympics

Order all countries by the year they first participated in the Olympics.
Output the National Olympics Committee (NOC) name along with the desired year.
Sort records by the year and the NOC in ascending order.

In [22]:
q.groupby(['NOC','region'])['Year'].min().reset_index()

NOC       region  Year
0    AFG  Afghanistan  1936
1    AHO      Curacao  1952
2    ALB      Albania  1972
3    ALG      Algeria  1964
4    AND      Andorra  1976
..   ...          ...   ...
221  YEM        Yemen  1992
222  YMD        Yemen  1988
223  YUG       Serbia  1920
224  ZAM       Zambia  1964
225  ZIM     Zimbabwe  1928

[226 rows x 3 columns]

# Median Age Of Gold Medal Winners

Find the median age of gold medal winners across all Olympics.




In [23]:
q[q.Medal.str.contains('Gold',na=False)].Age.mean()

25.90138395220449

# European Olympics
Find the number of athletes who participated in the Olympics that hosted in European cities.
European cities: Berlin, Athina, Lillehammer, London, Albertville and Paris.

In [24]:
q[q.City.str.contains('Berlin|Athina|Lillehammer|London|Albertville|Paris')].ID.count()

58194

# Average Weight of Medal-Winning Judo

Find the average weight of medal-winning Judo players of each team with a minimum age of 20 and a maximum age of 30. Consider players at the age of 20 and 30 too. Output the team along with the average player weight.




In [25]:
judo_medal_winning=q[(q.Sport=='Judo')&(q.Medal.str.contains('Gold|Bronze|Silver',na=False))]

In [26]:
avg_weight_judo_winning =judo_medal_winning[(judo_medal_winning.Age>=20)&(judo_medal_winning.Age<=30)].groupby(['NOC','region'])['Weight'].mean().reset_index()

In [27]:
avg_weight_judo_winning.rename(columns={'Weight':'avg_player_weight'}).head(5)

NOC      region  avg_player_weight
0  ALG     Algeria               71.0
1  ARG   Argentina               48.0
2  AUS   Australia               80.5
3  AUT     Austria               73.4
4  AZE  Azerbaijan               82.0

# Find all distinct sports that obese people participated in

Find all distinct sports that obese people participated in.
A person is considered as obese if his or her body mass index exceeds 30.
The body mass index is calculated as weight / (height * height). Use meters for height and kilograms for weight.

In [28]:
# add the BMI columns as above formula.
q['BMI']=q.Weight/((q.Height/100)*2)

In [29]:
# Filter the data with BMI > 30 and get the unique values of Sport columns
q[q.BMI>30]['Sport'].unique()

array(['Athletics', 'Synchronized Swimming', 'Wrestling', 'Weightlifting',
       'Basketball', 'Shooting', 'Judo', 'Boxing', 'Sailing', 'Rowing',
       'Bobsleigh', 'Tug-Of-War', 'Archery', 'Water Polo', 'Baseball',
       'Handball', 'Skeleton', 'Golf'], dtype=object)

# Find players who participated in the Olympics representing more than one team
Find players who participated in the Olympics representing more than one team.
Output the player name, team, games, sport, and the medal.


In [30]:
q.loc[q.duplicated(['Name','NOC','region']),['Name','Team','region','Games','Sport','Medal']]

Name     Team   region        Games  \
5                       Ai Yanhan    China    China  2016 Summer   
7                     An Weijiang    China    China  2006 Winter   
9                       An Yulong    China    China  1998 Winter   
10                      An Yulong    China    China  1998 Winter   
11                      An Yulong    China    China  2002 Winter   
...                           ...      ...      ...          ...   
270749  Tsepo Ramonene-Mathibelle  Lesotho  Lesotho  2016 Summer   
270754             Bothloko Shebe  Lesotho  Lesotho  1992 Summer   
270756       Lineo Florence Shoai  Lesotho  Lesotho  1996 Summer   
270757       Lineo Florence Shoai  Lesotho  Lesotho  2000 Summer   
270763            Mamorallo Tjoka  Lesotho  Lesotho  2012 Summer   

                            Sport   Medal  
5                        Swimming     NaN  
7                   Speed Skating     NaN  
9       Short Track Speed Skating     NaN  
10      Short Track Speed Skating  Bronze  
11      Short Track Speed Skating  Bronze  
...                           ...     ...  
270749                  Athletics     NaN  
270754                  Athletics     NaN  
270756                  Athletics     NaN  
270757                  Athletics     NaN  
270763                  Athletics     NaN  

[134337 rows x 6 columns]

# Find Olympics games that the youngest and the oldest athletes participated in the history of Olympics

Find Olympics games that the youngest and the oldest athletes participated in the history of Olympics.
Output all the details corresponding to each record.


In [31]:
# find the Olympics games that youngest athletes participated in the history of Olympics
q[q.Age==q.Age.max()]

ID                    Name Sex   Age  Height  Weight  \
32196  128719  John Quincy Adams Ward   M  97.0     NaN     NaN   

                Team  NOC        Games  Year  Season       City  \
32196  United States  USA  1928 Summer  1928  Summer  Amsterdam   

                  Sport                                        Event Medal  \
32196  Art Competitions  Art Competitions Mixed Sculpturing, Statues   NaN   

      region  BMI  
32196    USA  NaN

In [32]:
# find the Olympics games that oldest athletes participated in the history of Olympics
q[q.Age==q.Age.min()]

ID                Name Sex   Age  Height  Weight  \
99108  71691  Dimitrios Loundras   M  10.0     NaN     NaN   

                                Team  NOC        Games  Year  Season    City  \
99108  Ethnikos Gymnastikos Syllogos  GRE  1896 Summer  1896  Summer  Athina   

            Sport                                  Event   Medal  region  BMI  
99108  Gymnastics  Gymnastics Men's Parallel Bars, Teams  Bronze  Greece  NaN

In [33]:
# concat 2 results
pd.concat([q[q.Age==q.Age.max()],q[q.Age==q.Age.min()]])

ID                    Name Sex   Age  Height  Weight  \
32196  128719  John Quincy Adams Ward   M  97.0     NaN     NaN   
99108   71691      Dimitrios Loundras   M  10.0     NaN     NaN   

                                Team  NOC        Games  Year  Season  \
32196                  United States  USA  1928 Summer  1928  Summer   
99108  Ethnikos Gymnastikos Syllogos  GRE  1896 Summer  1896  Summer   

            City             Sport  \
32196  Amsterdam  Art Competitions   
99108     Athina        Gymnastics   

                                             Event   Medal  region  BMI  
32196  Art Competitions Mixed Sculpturing, Statues     NaN     USA  NaN  
99108        Gymnastics Men's Parallel Bars, Teams  Bronze  Greece  NaN

# Find the history of each sport by finding the first year, last year and total years that sport played in the Olympics
Find the history of each sport by finding the first year, last year, and the total number of years that sport played in the Olympics.
Output the sport name along with the first year, last year, and the total years.
Order records by the first year in descending order.

In [34]:
# find the first year of each sport played in Olympics: q.groupby('Sport').Year.min().reset_index()
# find the last year of each sport played in Olympics: q.groupby('Sport').Year.max().reset_index()
# find the total years of each sport played in Olympics: q.groupby('Sport').Year.count().reset_index()

In [35]:
# merge 3 tables to get final result
pd.merge(q.groupby('Sport').Year.min().reset_index(),q.groupby('Sport').Year.max().reset_index(),on='Sport').merge(
q.groupby('Sport').Year.count().reset_index(),on='Sport'
).rename(columns={'Year_x':'First year','Year_y':'Last year','Year':'Total years'})

Sport  First year  Last year  Total years
0        Aeronautics        1936       1936            1
1      Alpine Skiing        1936       2014         8829
2           Alpinism        1924       1936           25
3            Archery        1900       2016         2334
4   Art Competitions        1912       1948         3578
..               ...         ...        ...          ...
61        Tug-Of-War        1900       1920          170
62        Volleyball        1964       2016         3404
63        Water Polo        1900       2016         3836
64     Weightlifting        1896       2016         3926
65         Wrestling        1896       2016         7154

[66 rows x 4 columns]

# Olympics Gender Ratio


Find the gender ratio between the number of men and women who participated in each Olympics.
Output the Olympics name along with the corresponding number of men, women, and the gender ratio. If there are Olympics with no women, output a NULL instead of a ratio.


In [36]:
gender=q[q.Sex=='M'].groupby('Games')['ID'].count().reset_index().merge(
    q[q.Sex=='F'].groupby('Games')['ID'].count().reset_index(),on='Games').rename(columns=
                                                                                  {'ID_x':'Total Male','ID_y':'Total Female'})
gender.head()

Games  Total Male  Total Female
0  1900 Summer        1903            33
1  1904 Summer        1285            16
2  1906 Summer        1722            11
3  1908 Summer        3054            47
4  1912 Summer        3953            87

In [37]:
gender['Male_pct']=(gender['Total Male']/(gender['Total Male']+gender['Total Female'])*100).round(2)
gender['Female_pct']=(gender['Total Female']/(gender['Total Male']+gender['Total Female'])*100).round(2)

In [38]:
gender.head()

Games  Total Male  Total Female  Male_pct  Female_pct
0  1900 Summer        1903            33     98.30        1.70
1  1904 Summer        1285            16     98.77        1.23
2  1906 Summer        1722            11     99.37        0.63
3  1908 Summer        3054            47     98.48        1.52
4  1912 Summer        3953            87     97.85        2.15

# Find how the average male height changed between each Olympics from 1896 to 2016

Find how the average male height changed between each Olympics from 1896 to 2016.
Output the Olympics year, average height, previous average height, and the corresponding average height difference.
Order records by the year in ascending order.


If avg height is not found, assume that the average height of an athlete is 172.73.

In [39]:
avg_height=q[(q.Sex=='M')&(q.Year>=1896)&(q.Year<=2016)].groupby('Year')['Height'].mean().reset_index().sort_values('Year')
avg_height.head()

Year      Height
0  1896  172.739130
1  1900  176.637931
2  1904  175.788732
3  1906  178.206226
4  1908  177.543158

In [40]:
avg_height['previous_height']=avg_height.Height.shift(1)

In [41]:
avg_height['height_diff']=avg_height.Height.diff()

In [42]:
avg_height

Year      Height  previous_height  height_diff
0   1896  172.739130              NaN          NaN
1   1900  176.637931       172.739130     3.898801
2   1904  175.788732       176.637931    -0.849199
3   1906  178.206226       175.788732     2.417493
4   1908  177.543158       178.206226    -0.663068
5   1912  177.447989       177.543158    -0.095169
6   1920  176.144772       177.447989    -1.303217
7   1924  175.418085       176.144772    -0.726687
8   1928  175.840223       175.418085     0.422138
9   1932  174.931942       175.840223    -0.908282
10  1936  176.564055       174.931942     1.632113
11  1948  177.254634       176.564055     0.690579
12  1952  176.496880       177.254634    -0.757754
13  1956  176.360205       176.496880    -0.136675
14  1960  175.403202       176.360205    -0.957003
15  1964  175.594406       175.403202     0.191204
16  1968  176.355959       175.594406     0.761554
17  1972  177.191317       176.355959     0.835357
18  1976  177.722588       177.191317     0.531271
19  1980  178.458705       177.722588     0.736117
20  1984  178.550464       178.458705     0.091759
21  1988  179.101999       178.550464     0.551534
22  1992  179.753352       179.101999     0.651354
23  1994  179.442791       179.753352    -0.310561
24  1996  180.137211       179.442791     0.694420
25  1998  179.559041       180.137211    -0.578171
26  2000  180.710241       179.559041     1.151200
27  2002  179.715706       180.710241    -0.994535
28  2004  180.894837       179.715706     1.179131
29  2006  179.845361       180.894837    -1.049476
30  2008  181.257728       179.845361     1.412367
31  2010  180.432824       181.257728    -0.824904
32  2012  181.638654       180.432824     1.205830
33  2014  180.261738       181.638654    -1.376916
34  2016  181.555828       180.261738     1.294090

# Olympic Medals By Chinese Athletes


Find the number of medals earned in each category by Chinese athletes from the 2000 to 2016 summer Olympics. For each medal category, calculate the number of medals for each olympic games along with the total number of medals across all years. Sort records by total medals in descending order.

In [43]:
cn_medal=q[(q.Year<=2016)&(q.Year>=2000)&(q.Season=='Summer')&(q.NOC=='CHN')].groupby('Games').Medal.value_counts().reset_index(name='count')
cn_medal.head()

Games   Medal  count
0  2000 Summer    Gold     39
1  2000 Summer  Silver     23
2  2000 Summer  Bronze     17
3  2004 Summer    Gold     52
4  2004 Summer  Silver     27

In [44]:
cn_medal1=pd.pivot(cn_medal,index='Games',columns='Medal',values='count').reset_index()
cn_medal1

Medal        Games  Bronze  Gold  Silver
0      2000 Summer      17    39      23
1      2004 Summer      15    52      27
2      2008 Summer      57    74      53
3      2012 Summer      29    56      40
4      2016 Summer      37    46      30

In [45]:
cn_medal1['Total']=cn_medal1['Bronze']+cn_medal1['Bronze']+cn_medal1['Bronze']
cn_medal1

Medal        Games  Bronze  Gold  Silver  Total
0      2000 Summer      17    39      23     51
1      2004 Summer      15    52      27     45
2      2008 Summer      57    74      53    171
3      2012 Summer      29    56      40     87
4      2016 Summer      37    46      30    111

# Top Teams In The Rio De Janeiro 2016 Olympics

Find the top 3 medal-winning teams by counting the total number of medals for each event in the Rio De Janeiro 2016 olympics. In case there is a tie, order the countries by name in ascending order. Output the event name along with the top 3 teams as the 'gold team', 'silver team', and 'bronze team', with the team name and the total medals under each column in format "{team} with {number of medals} medals". Replace NULLs with "No Team" string.

In [46]:
olym_2016_total= q[q.Medal.str.contains('Gold|Silver|Bronze',na=False)&(q.Year==2016)].groupby(
    'region')['Medal'].value_counts().reset_index(name='total')
olym_2016_total

region   Medal  total
0       Algeria  Silver      2
1     Argentina    Gold     21
2     Argentina  Silver      1
3       Armenia  Silver      3
4       Armenia    Gold      1
..          ...     ...    ...
183  Uzbekistan  Silver      2
184   Venezuela  Bronze      2
185   Venezuela  Silver      1
186     Vietnam    Gold      1
187     Vietnam  Silver      1

[188 rows x 3 columns]

In [47]:
olym_2016_total=pd.pivot(olym_2016_total,columns='Medal',values='total',index='region').reset_index().fillna(0)
olym_2016_total

Medal                region  Bronze  Gold  Silver
0                   Algeria     0.0   0.0     2.0
1                 Argentina     0.0  21.0     1.0
2                   Armenia     0.0   1.0     3.0
3                 Australia    25.0  23.0    34.0
4                   Austria     2.0   0.0     0.0
..                      ...     ...   ...     ...
80                  Ukraine     5.0   2.0     8.0
81     United Arab Emirates     1.0   0.0     0.0
82               Uzbekistan     7.0   4.0     2.0
83                Venezuela     2.0   0.0     1.0
84                  Vietnam     0.0   1.0     1.0

[85 rows x 4 columns]

In [48]:
olym_2016_total['Total']=olym_2016_total.Bronze+olym_2016_total.Gold+olym_2016_total.Silver

In [49]:
olym_2016_total.loc[:,['region','Total','Gold','Silver','Bronze']].sort_values('Total',ascending=False)

Medal       region  Total   Gold  Silver  Bronze
79             USA  264.0  139.0    54.0    71.0
28         Germany  159.0   49.0    43.0    67.0
78              UK  145.0   64.0    55.0    26.0
63          Russia  115.0   52.0    28.0    35.0
14           China  113.0   46.0    30.0    37.0
..             ...    ...    ...     ...     ...
50         Morocco    1.0    0.0     0.0     1.0
53           Niger    1.0    0.0     1.0     0.0
57     Philippines    1.0    0.0     1.0     0.0
59        Portugal    1.0    0.0     0.0     1.0
42          Jordan    1.0    1.0     0.0     0.0

[85 rows x 5 columns]

# Athletes On Single Or Multiple Teams

Classify each athlete as either on one team or on multiple teams based on the number of team names in the 'team' column. If an athlete is only on one team, classify them as 'One Team', otherwise classify the athlete as 'Multiple Teams'. Athletes on multiple teams will have two teams listed and separated by a / (e.g., Denmark/Sweden). Output unique player names along with the classification.

In [50]:
q['classification']='One Team'

In [51]:
q.loc[q.Team.str.contains('/'),'classification']='Multiple Teams'

In [52]:
q.loc[:,['Name','classification']]

Name classification
0                A Dijiang       One Team
1                 A Lamusi       One Team
2            Abudoureheman       One Team
3                Ai Linuer       One Team
4                Ai Yanhan       One Team
...                    ...            ...
270762     Mamorallo Tjoka       One Team
270763     Mamorallo Tjoka       One Team
270764  M'apotlaki Ts'elho       One Team
270765          Lefa Tsapi       One Team
270766       Mosolesa Tsie       One Team

[270767 rows x 2 columns]

In [53]:
q.classification.value_counts()

One Team          270724
Multiple Teams        43
Name: classification, dtype: int64

# Name to Medal Connection

Find the connection between the number of letters in the athlete's first name and the number of medals won for each type for medal, including no medals. Output the length of the name along with the corresponding number of no medals, bronze medals, silver medals, and gold medals.

In [54]:
q['name_length']=q.Name.str.len()

In [55]:
q.Medal.fillna('no medals',inplace=True)

In [56]:
q.groupby('name_length').Medal.value_counts().reset_index(name='count')

name_length      Medal  count
0              2  no medals      4
1              3  no medals      4
2              4  no medals     18
3              4     Bronze      1
4              5  no medals    123
..           ...        ...    ...
259           93  no medals      2
260           93     Silver      1
261           97  no medals      1
262          100  no medals      2
263          108  no medals      1

[264 rows x 3 columns]